// var myAssertThrows = function (funcThatShouldThrow, errorType) {
//     try {
//         funcThatShouldThrow();
//     } catch (TypeError) {
//         console.log("All is good. Function failed with " + errorType);
//         return true;
//     }
//     console.log("Something went wrong,  function didn't fail with " + errorType);
//     return false;
// }

// var f = function die(){
//     throw TypeError("Aaaaaa!!!1111")
// }

// myAssertThrows(f, TypeError);


